# Generated by Django 2.0 on 2018-09-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='rating_writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='writers.Rating'),
            preserve_default=False,
        ),
    ]
