# Generated by Django 2.0 on 2018-09-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0002_orders_rating_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='rating_writer',
        ),
        migrations.AddField(
            model_name='rating',
            name='num_of_orders_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
